### ISSUE TITLE
Need more doc about which files are actually bundled

### ISSUE THREAD

**Issue by steph643** [zodern/mup-node#1]
The doc says:
>Bundling
>mup-node copies the app's files to the server. The .git and node_module directories are ignored.

Does it mean *any* file from the app folder (except .git and node_module) is bundled? Including, for example, my `/.deploy` folder containing `mup.js` and `settings.json`?

**Comment by zodern** [comment]
Yes, it includes any file not in those two folders. It probably should remove the mup config. Most node apps don't have a `settings.json`.

I am planning to allow configuring additional files or folders to be ignored.

**Comment by zodern** [comment]
You can now use a .mupignore file to exclude additional folders and files.
